steps:
  # Step 1: Produce output
  - label: ":hammer: Build & Generate Output"
    command: "./build.sh"
    key: "build"

  # Step 2: Run verification (can be flaky)
  - label: ":test_tube: Verification Tests"
    command: "./verification.sh"
    key: "verification"
    depends_on: "build"
    soft_fail: true

  # Wait for verification to complete, but continue even if it fails
  - wait: ~
    continue_on_failure: true

  # Step 3: Manual override input (always shows)
  - block: ":question: Review Results"
    prompt: |
      Build completed. Review the verification results above.
      
      If verification passed: Click 'Continue' to proceed.
      If verification failed: Verify manually that it's safe to proceed, then click 'Continue'.
    fields:
      - select: "Action"
        key: "action"
        required: true
        options:
          - label: "Continue to deploy"
            value: "continue"
          - label: "Stop here"
            value: "stop"

  # Final step: Deploy (only if user chose to continue)
  - label: ":rocket: Deploy"
    command: |
      ACTION=$$(buildkite-agent meta-data get "action")
      if [ "$$ACTION" = "continue" ]; then
        echo "Deploying..."
        echo "Deployment complete!"
      else
        echo "Deployment cancelled by user"
        exit 1
      fi