steps:
  - label: "Detect Namespace CLI"
    agents:
      queue: default
    command: |
      if NSC_PATH=$(which nsc 2>/dev/null); then
        echo "nsc found at ${NSC_PATH}"
      elif [ -x /root/.ns/bin/nsc ]; then
        echo "nsc found at /root/.ns/bin/nsc"
      else
        echo "Namespace CLI not found" >&2
        exit 1
      fi

  # - label: ":docker: Build with Namespace"
  #   agents:
  #     queue: default
  #   command: |
  #     nsc auth exchange-aws-cognito-token \
  #       --aws_region us-east-1 \
  #       --identity_pool us-east-1:217947c4-e20e-4315-97f8-08e9a14c8dfb \
  #       --tenant_id tenant_uabmve166l99o

  #     nsc docker buildx setup --background --use
  #     nsc docker login
  #     docker buildx build \
  #       --builder nsc-remote \
  #       --platform linux/amd64,linux/arm64 \
  #       -t nscr.io/uabmve166l99o/sample-app:latest \
  #       --push \
  #       .

  #     # Alternative: push to another registry
  #     # docker buildx build \
  #     #   --builder nsc-remote \
  #     #   --platform linux/amd64,linux/arm64 \
  #     #   -t nscr.io/uabmve166l99o/<image-name>:latest \
  #     #   --push \
  #     #   .
      

