steps:
  - label: ":docker: Build with Namespace"
    agents:
      queue: default
    command: |
      set -euo pipefail
      if [ ! -x "/usr/local/bin/nsc" ]; then
        echo "Namespace CLI not available at /usr/local/bin/nsc" >&2
        exit 1
      fi
      /usr/local/bin/nsc auth exchange-aws-cognito-token \
        --aws_region us-east-1 \
        --identity_pool us-east-1:217947c4-e20e-4315-97f8-08e9a14c8dfb \
        --tenant_id tenant_uabmve166l99o

      /usr/local/bin/nsc docker buildx setup --background --use
      /usr/local/bin/nsc docker login
      docker buildx build \
        --builder nsc-remote \
        --platform linux/amd64,linux/arm64 \
        -t 097340723131.dkr.ecr.us-east-1.amazonaws.com/your-repo:latest \
        --push \
        .

      # Alternative: push to another registry
      # docker buildx build \
      #   --builder nsc-remote \
      #   --platform linux/amd64,linux/arm64 \
      #   -t nscr.io/uabmve166l99o/<image-name>:latest \
      #   --push \
      #   .
      

