steps:
  - label: "Install Namespace CLI"
    agents:
      queue: default
    command: |
      set -euo pipefail

      curl -fsSL https://get.namespace.so/cloud/install.sh | sh

      if [ -x /root/.ns/bin/nsc ]; then
        sudo install -m 755 /root/.ns/bin/nsc /usr/local/bin/nsc
        sudo chown buildkite-agent:buildkite-agent /usr/local/bin/nsc
      fi

      if ! command -v nsc >/dev/null 2>&1; then
        echo "Namespace CLI installation failed" >&2
        exit 1
      fi

  - label: "Detect Namespace CLI"
    agents:
      queue: default
    command: |
      set -euo pipefail

      NSC_PATH=$(which nsc 2>/dev/null)
      if [ -n "${NSC_PATH}" ]; then
        echo "nsc found at ${NSC_PATH}"
      else
        echo "Namespace CLI not found" >&2
        exit 1
      fi

  # - label: ":docker: Build with Namespace"
  #   agents:
  #     queue: default
  #   command: |
  #     nsc auth exchange-aws-cognito-token \
  #       --aws_region us-east-1 \
  #       --identity_pool us-east-1:217947c4-e20e-4315-97f8-08e9a14c8dfb \
  #       --tenant_id tenant_uabmve166l99o

  #     nsc docker buildx setup --background --use
  #     nsc docker login
  #     docker buildx build \
  #       --builder nsc-remote \
  #       --platform linux/amd64,linux/arm64 \
  #       -t nscr.io/uabmve166l99o/sample-app:latest \
  #       --push \
  #       .

  #     # Alternative: push to another registry
  #     # docker buildx build \
  #     #   --builder nsc-remote \
  #     #   --platform linux/amd64,linux/arm64 \
  #     #   -t nscr.io/uabmve166l99o/<image-name>:latest \
  #     #   --push \
  #     #   .
      

