steps:
  - label: ":hammer_and_wrench: Install Namespace CLI"
    agents:
      queue: default
    command: |
      set -euo pipefail

      curl -fsSL https://get.namespace.so/cloud/install.sh | sh

      if [ ! -x /var/lib/buildkite-agent/.ns/bin/nsc ]; then
        echo "Namespace CLI install failed" >&2
        exit 1
      fi

      cat <<'EOF' >> "$BUILDKITE_ENV_FILE"
      export PATH="/var/lib/buildkite-agent/.ns/bin:$PATH"
      export NSC_BIN="/var/lib/buildkite-agent/.ns/bin/nsc"
      EOF

  - label: ":mag: Detect Namespace CLI"
    agents:
      queue: default
    command: |
      set -euo pipefail

      NSC_BIN="${NSC_BIN:-/var/lib/buildkite-agent/.ns/bin/nsc}"
      if [ -x "$NSC_BIN" ]; then
        echo "nsc found at $NSC_BIN"
        "$NSC_BIN" --version
      else
        echo "Namespace CLI not found" >&2
        exit 1
      fi

  # - label: ":docker: Build with Namespace"
  #   agents:
  #     queue: default
  #   command: |
  #     set -euo pipefail
  #     NSC_BIN="${NSC_BIN:-/var/lib/buildkite-agent/.ns/bin/nsc}"
  #     if [ ! -x "$NSC_BIN" ]; then
  #       echo "Namespace CLI not available" >&2
  #       exit 1
  #     fi
  #     "$NSC_BIN" auth exchange-aws-cognito-token \
  #       --aws_region us-east-1 \
  #       --identity_pool us-east-1:217947c4-e20e-4315-97f8-08e9a14c8dfb \
  #       --tenant_id tenant_uabmve166l99o

  #     "$NSC_BIN" docker buildx setup --background --use
  #     "$NSC_BIN" docker login
  #     docker buildx build \
  #       --builder nsc-remote \
  #       --platform linux/amd64,linux/arm64 \
  #       -t nscr.io/uabmve166l99o/sample-app:latest \
  #       --push \
  #       .

  #     # Alternative: push to another registry
  #     # docker buildx build \
  #     #   --builder nsc-remote \
  #     #   --platform linux/amd64,linux/arm64 \
  #     #   -t nscr.io/uabmve166l99o/<image-name>:latest \
  #     #   --push \
  #     #   .
      

