env:
  PIPELINE_SECRET: "pipeline-level-secret"

steps:
  - label: "Broken - interpolated"
    command: echo "Secret is $MY_SECRET"
    
  - label: "Working - escaped dollar"
    command: echo "Secret is $$MY_SECRET"
    env:
      MY_SECRET: "hvs.CAESIXFXBZW"
      
  - label: "Working - hardcoded redacted"
    command: echo "Secret is [REDACTED]"
    
  - label: "Working - no interpolation"
    command: echo "Secret is $MY_SECRET"
    env:
      MY_SECRET: "hvs.CAESIXFXBZW"
      
  - label: "Test pipeline level env"
    command: echo "Pipeline env $PIPELINE_SECRET"
