steps:
  - label: 'Step 1'
    command: "false"
    key: 'one'

  - wait:
    continue_on_failure: true

  - label: 'Step 2'
    command: |
      if [ $? -eq 0 ]; then
        MESSAGE="✅ All tests passed! Coverage: 95%"
      else
        MESSAGE="❌ Tests failed. See report for details."
      fi
      
      # Set metadata
      buildkite-agent meta-data set "test-summary" "$$MESSAGE"

notify:
  - slack: "#ola-testing"
    message: "echo $$MESSAGE"
