env:
  BUILDKITE_GIT_CHECKOUT_FLAGS: "-f"
  BUILDKITE_COMMAND_EVAL: "true"
  BUILDKITE_LOCAL_HOOKS_ENABLED: "false"
  BUILDKITE_PLUGINS_ENABLED: "true"
  BUILDKITE_SHELL: "/bin/bash"

steps:
  # Docker Plugin Tests
  - label: ":docker: Docker Plugin - With Experiment (Mac)"
    key: "docker-with-experiment"
    agents:
      queue: "mac"
    plugins:
      - docker#v5.11.0:
          image: "alpine:3.18"
          propagate-environment: true
    command: |
      echo "=== Docker Plugin with Experiment ==="
      echo "Agent config vars from experiment list:"
      env | grep -E '^BUILDKITE_(GIT_CHECKOUT_FLAGS|GIT_CLEAN_FLAGS|GIT_CLONE_FLAGS|GIT_MIRRORS_|CANCEL_GRACE_PERIOD|COMMAND_EVAL|LOCAL_HOOKS_ENABLED|PLUGINS_ENABLED|REDACTED_VARS|SHELL|SIGNAL_GRACE_PERIOD|SSH_KEYSCAN|STRICT_SINGLE_HOOKS|TRACE_|TRACING_|AGENT_AWS_KMS_KEY|AGENT_JWKS_)' | sort || echo 'No experiment agent config vars found'
      echo "Total BUILDKITE_ vars: $(env | grep '^BUILDKITE_' | wc -l)"

  - label: ":docker: Docker Plugin - Without Experiment (Linux)"
    key: "docker-without-experiment"
    agents:
      queue: "linux"
    plugins:
      - docker#v5.11.0:
          image: "alpine:3.18"
          propagate-environment: true
    command: |
      echo "=== Docker Plugin without Experiment ==="
      echo "Agent config vars from experiment list:"
      env | grep -E '^BUILDKITE_(GIT_CHECKOUT_FLAGS|GIT_CLEAN_FLAGS|GIT_CLONE_FLAGS|GIT_MIRRORS_|CANCEL_GRACE_PERIOD|COMMAND_EVAL|LOCAL_HOOKS_ENABLED|PLUGINS_ENABLED|REDACTED_VARS|SHELL|SIGNAL_GRACE_PERIOD|SSH_KEYSCAN|STRICT_SINGLE_HOOKS|TRACE_|TRACING_|AGENT_AWS_KMS_KEY|AGENT_JWKS_)' | sort || echo 'No experiment agent config vars found'
      echo "Total BUILDKITE_ vars: $(env | grep '^BUILDKITE_' | wc -l)"

  - label: ":docker: Docker Compose Plugin - With Experiment (Mac)"
    key: "docker-compose-with-experiment"
    agents:
      queue: "mac"
    plugins:
      - docker-compose#v4.16.0:
          config: docker-compose.yml
          run: app
          propagate-environment: true
    command: |
      echo "=== Docker Compose Plugin with Experiment ==="
      echo "Agent config vars from experiment list:"
      env | grep -E '^BUILDKITE_(GIT_CHECKOUT_FLAGS|GIT_CLEAN_FLAGS|GIT_CLONE_FLAGS|GIT_MIRRORS_|CANCEL_GRACE_PERIOD|COMMAND_EVAL|LOCAL_HOOKS_ENABLED|PLUGINS_ENABLED|REDACTED_VARS|SHELL|SIGNAL_GRACE_PERIOD|SSH_KEYSCAN|STRICT_SINGLE_HOOKS|TRACE_|TRACING_|AGENT_AWS_KMS_KEY|AGENT_JWKS_)' | sort || echo 'No experiment agent config vars found'
      echo "Total BUILDKITE_ vars: $(env | grep '^BUILDKITE_' | wc -l)"

  - label: ":docker: Docker Compose Plugin - Without Experiment (Linux)"
    key: "docker-compose-without-experiment"
    agents:
      queue: "linux"
    plugins:
      - docker-compose#v4.16.0:
          config: docker-compose.yml
          run: app
          propagate-environment: true
    command: |
      echo "=== Docker Compose Plugin without Experiment ==="
      echo "Agent config vars from experiment list:"
      env | grep -E '^BUILDKITE_(GIT_CHECKOUT_FLAGS|GIT_CLEAN_FLAGS|GIT_CLONE_FLAGS|GIT_MIRRORS_|CANCEL_GRACE_PERIOD|COMMAND_EVAL|LOCAL_HOOKS_ENABLED|PLUGINS_ENABLED|REDACTED_VARS|SHELL|SIGNAL_GRACE_PERIOD|SSH_KEYSCAN|STRICT_SINGLE_HOOKS|TRACE_|TRACING_|AGENT_AWS_KMS_KEY|AGENT_JWKS_)' | sort || echo 'No experiment agent config vars found'
      echo "Total BUILDKITE_ vars: $(env | grep '^BUILDKITE_' | wc -l)"

  # Summary step
  - label: "📊 Test Summary"
    key: "summary"
    depends_on:
      - "docker-with-experiment"
      - "docker-without-experiment"
      - "docker-compose-with-experiment"
      - "docker-compose-without-experiment"
    command: |
      echo "=== Test Summary ==="
      echo "Compare the agent config variables above between Mac (with experiment) and Linux (without experiment) queues."
      echo "Expected: Mac (with experiment) should show agent config vars, Linux (without experiment) should not."
