steps:
  - command: |
      echo "=== STEP 1: Setting metadata ==="
      echo "About to set target-branch to slack"
      buildkite-agent meta-data set "target-branch" "slack"
      echo "Metadata set command completed"
      echo "Verifying metadata was set..."
      VERIFY=$(buildkite-agent meta-data get "target-branch")
      echo "Verification result: '$VERIFY'"
      if [ "$VERIFY" = "slack" ]; then
        echo "✅ Metadata set successfully!"
      else
        echo "❌ Metadata setting failed!"
      fi
    label: "Step 1: Set and verify metadata"
    
  - wait
    
  - command: |
      echo "=== STEP 2: Getting metadata ==="
      echo "All available metadata keys:"
      buildkite-agent meta-data keys
      TARGET_BRANCH=$(buildkite-agent meta-data get "target-branch")
      echo "Retrieved target branch: '$TARGET_BRANCH'"
      # ... rest of your step
    label: "Step 2: Debug and use metadata"