steps:
  - label: "Simple wildcard download"
    command: |
      echo "Downloading all artifacts from known working build..."
      
      # Use your known working build ID
      KNOWN_BUILD="01978480-cbba-4ee5-89a2-930febebc318"
      
      buildkite-agent artifact download "*" ./all-artifacts/ --build "$KNOWN_BUILD"
      
      echo "Downloaded files:"
      find ./all-artifacts/ -type f -ls 2>/dev/null || echo "No files found"
      
      echo "File contents:"
      find ./all-artifacts/ -type f -exec echo "=== {} ===" \; -exec cat {} \; 2>/dev/null