steps:
  - label: "Test Build with Sections and Links"
    command: |
      echo "--- :rocket: Starting build process"
      echo "This is the main build step"
      
      echo "--- :information_source: Build Information"
      echo "Build number: ${BUILDKITE_BUILD_NUMBER}"
      echo "Branch: ${BUILDKITE_BRANCH}"
      echo "Repository: https://github.com/example/repo"
      echo "Documentation: [Click here](https://docs.example.com)"
      echo "HTML link attempt: <a href='https://buildkite.com'>Buildkite</a>"
      
      echo "--- :test_tube: Running Tests"
      echo "Test results will appear here"
      echo "View full report: https://reports.example.com/test-${BUILDKITE_BUILD_NUMBER}"
      
      echo "--- :white_check_mark: Build Complete"
      echo "Artifacts available at: https://artifacts.example.com/build-${BUILDKITE_BUILD_NUMBER}"
      echo "Markdown link: [Download artifacts](https://artifacts.example.com/build-${BUILDKITE_BUILD_NUMBER})"

  - label: "Deploy"
    command: |
      echo "--- :rocket: Deployment"
      echo "Deploying to staging..."
      echo "View deployment: https://staging.example.com"
      echo "Dashboard: [Staging Dashboard](https://dashboard.staging.example.com)"
    
    depends_on: "test-build-with-sections-and-links"