steps:
  - command: aws sts get-caller-identity
    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn:   arn:aws:iam::097340723131:role/ola-sts-assume-role

  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test

  - label: ":arrow_right: Triggering post-deploy verifier"
    command: |
      ./src/post-release-trigger.sh
    depends_on: deploy