agents:
      queue: "mac"

steps:
  - label: "Step 1 - Main Task"
    key: "step1"
    command: |
      echo "Running main task"
      # Your actual command here that might fail

  - wait

  - label: "Check Step 1 and Upload Conditional Step"
    command: |
      if [ "$(buildkite-agent step get "outcome" --step "step1")" == "failed" ] || [ "$(buildkite-agent step get "outcome" --step "step1")" == "hard_failed" ]; then
        cat <<- YAML | buildkite-agent pipeline upload
      steps:
        - label: "Step 2 - Fallback Task"
          command: |
            echo "Step 1 failed, running fallback"
            # Your fallback logic here
      YAML
      else
        echo "Step 1 succeeded, skipping fallback step"
      fi