steps:
  - env:
      BUILD_JOB_PROJECT: "myproject"
    key: "execute_build_units_Generate-pipeline-e7e1"
    label: "Generate pipeline"
    retry:
      automatic:
        - limit: 2
          exit_status: -1
        - limit: 2
          exit_status: 255
        - limit: 2
          exit_status: 128
    agents:
      queue: "default"
    commands:
      - |
        if [ -n "$BUILDKITE_LABEL" ]; then
          buildkite-agent meta-data set "$BUILDKITE_LABEL" "true"
        fi
      - "export PS4='$'"
      - "echo 'steps:' > dynamic-pipeline.yml"
      - "echo '  - label: Dynamic Step Success' >> dynamic-pipeline.yml"
      - "echo '    command: echo Hello from generated pipeline' >> dynamic-pipeline.yml"
      - "echo '  - label: Dynamic Step Failure' >> dynamic-pipeline.yml"
      - "echo '    command: exit 1' >> dynamic-pipeline.yml"
      - "buildkite-agent pipeline upload dynamic-pipeline.yml"
notify:
  - if: "build.state == \"failed\""
    slack:
      message: "Build failure: Pipeline Generation"
      channels:
        - "#all-testing"