steps:
  - label: "Test Success Job"
    command: |
      echo "This job will succeed"
      sleep 10
      echo "Success completed!"
    agents:
      queue: "mac"

  - label: "Another Success Job"
    command: |
      echo "This job will also succeed"
      sleep 5
      echo "All good!"
    agents:
      queue: "mac"

notify:
  - email: "your-email@example.com"
    if: build.state == "passed"
  - email: "your-email@example.com"
    if: build.state == "failed"