steps:
  - label: "Test Success Job"
    agents:
      queue: "mac"
    command: "echo \"This job will succeed\"\nsleep 10\necho \"Success completed!\"\n"
  - label: "Another Success Job"
    agents:
      queue: "mac"
    command: "echo \"This job will also succeed\"\nsleep 5\necho \"All good!\"\n"

notify:
  - slack:
      channels:
        - "#ola-testing"
      message: "This message will ping the user with <@michael.omoge>!"
