agents:
      queue: "mac"

steps:
  - label: "Step 1 - Main Task"
    key: "step1"
    command: |
      echo "Running main task"
      # Your actual command here

  - label: "Step 2 - Fallback Task"
    key: "step2"
    depends_on: 
      - step: "step1"
        allow_dependency_failure: "true"
    if: build.jobs.step1.state == "failed"
    command: |
      echo "Step 1 failed, running fallback"