agents:
  queue: "mac"
steps:
  - name: ":docker: Test with propagate-environment"
    command: |
      echo "--- Container Environment"
      env | grep -E 'BUILDKITE|OTEL' | sort
    plugins:
      - docker#v5.12.0:
          image: "alpine:3.18"
          propagate-environment: true
          shell: ["/bin/sh", "-ec"]
