agents:
  queue: "mac"
  
steps:
  - label: "Build"
    key: "build-step"
    command: |
      echo "Building..."
      echo "DEPRECATION WARNING: old build method used"
      echo "Build completed"
    
  - label: "Tests"  
    key: "test-step"
    command: |
      echo "Running tests..."
      echo "DEPRECATION: test framework will be updated"
      echo "Another DEPRECATION WARNING: old assertion method"
      echo "Tests completed"
    
  - label: "Deploy"
    key: "deploy-step"
    command: |
      echo "Deploying..."
      echo "Deploy completed"
    
  - wait
  
  - label: "Analyze Test Logs"
    command: |
      echo "Starting log analysis..."
      # Your API calls here