agents:
  queue: "mac"
  
steps:
  - label: ":mag: Host Environment"
    command: |
      echo "Host BUILDKITE_* count: $$(env | grep -c BUILDKITE)"

  - label: ":docker: Before Fix"
    plugins:
      - docker#v5.12.0:
          image: "alpine:3.18"
          propagate-environment: true
    command: |
      echo "Before fix count: $$(env | grep -c BUILDKITE)"

  - label: ":docker: After Fix"
    plugins:
      - github.com/Mykematt/docker-buildkite-plugin#sup-4218-signing-vars-fix:
          image: "alpine:3.18"
          propagate-environment: true
    command: |
      echo "After fix count: $$(env | grep -c BUILDKITE)"

  - label: ":docker: Docker Compose Fix"
    plugins:
      - github.com/Mykematt/docker-compose-buildkite-plugin#sup-4218-signing-vars-fix:
          run: app
          propagate-environment: true
    command: |
      echo "Docker Compose count: $$(env | grep -c BUILDKITE)"
