steps:
  - command: |
      echo "Setting target branch metadata"
      buildkite-agent meta-data set "target-branch" "slack"
      echo "Metadata set successfully"
      echo "Current branch: $BUILDKITE_BRANCH"
    label: "Step 1: Set metadata"
    
  - wait
    
  - command: |
      echo "Getting target branch from metadata"
      TARGET_BRANCH=$(buildkite-agent meta-data get "target-branch")
      if [ -z "$TARGET_BRANCH" ]; then
        echo "ERROR: No target branch found in metadata!"
        exit 1
      fi
      echo "Target branch from metadata: $TARGET_BRANCH"
      git fetch origin "$TARGET_BRANCH"
      git checkout "$TARGET_BRANCH"
      echo "Now on branch: $(git branch --show-current)"
    label: "Step 2: Use metadata"