steps:
  - label: "Generate test file"
    command: |
      echo "Creating test data file..."
      
      # Create a test file with some data
      echo "Build ID: $BUILDKITE_BUILD_ID" > test-data.txt
      echo "Build Number: $BUILDKITE_BUILD_NUMBER" >> test-data.txt
      echo "Pipeline: $BUILDKITE_PIPELINE_SLUG" >> test-data.txt
      echo "Generated at: $(date)" >> test-data.txt
      echo "Some test data for cross-pipeline usage" >> test-data.txt
      
      # Show what we created
      echo "Generated file contents:"
      cat test-data.txt
      
      # Upload as artifact
      buildkite-agent artifact upload "test-data.txt"
      
      echo "✅ Artifact uploaded successfully"
      echo "Build UUID: $BUILDKITE_BUILD_ID"