steps:
  # Simple trigger pipeline
  - label: ":rocket: Trigger Self Pipeline"
    trigger: "starter"
    build:
      message: "Self-triggered from starter pipeline"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    key: "trigger"