steps:
  # Simple trigger pipeline
  - label: ":rocket: Trigger Downstream Pipeline"
    trigger: "bash-parallel-example"
    build:
      message: "Triggered from main pipeline"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    key: "trigger"