notify:
  - github_commit_status:
      context: "buildkite/my-pipeline-testing"
    if: build.branch == "main"
    
steps:
  - label: ":hammer: Build"
    command: |
      echo "Building on branch: \$BUILDKITE_BRANCH"
    
  - label: ":test_tube: Tests"
    command: |
      echo "Running tests..."
      sleep 5
      echo "Tests passed!"
