steps:
  - label: ":camera_with_flash:"
    command: "ls -al images/*.png"
    artifact_paths:
      - "./images/*.png"
    key: upload
    agents:
      queue: "default"    
  - label: ":package:"
    command: "./src/inspect-image-artifacts.sh"
    depends_on: upload
    agents:
      queue: "mac"
