steps:
  - command: |
      echo "Setting target branch metadata"
      buildkite-agent meta-data set "target-branch" "slack"
      echo "Current branch: $BUILDKITE_BRANCH"
      # Replace with your actual build commands
      echo "Building on current branch..."
      ls -la  # Just to show we're doing something
    label: "Build current branch & set metadata"
    
  - wait
    
  - command: |
      TARGET_BRANCH=$(buildkite-agent meta-data get "target-branch")
      echo "Target branch from metadata: $TARGET_BRANCH"
      git fetch origin "$TARGET_BRANCH"
      git checkout "$TARGET_BRANCH"
      echo "Now on branch: $(git branch --show-current)"
      # Replace with your actual build commands
      echo "Building on target branch..."
      ls -la  # Just to show the checkout worked
    label: "Build target branch from metadata"