steps:
  - env:
      BUILD_JOB_PROJECT: "myproject"
    key: "execute_build_units_Generate-pipeline-e7e1"
    label: "Generate pipeline"
    retry:
      automatic:
        - limit: 2
          exit_status: -1
        - limit: 2
          exit_status: 255
        - limit: 2
          exit_status: 128
    agents:
      queue: "default"
    command: "exit 1"
    notify:
      - if: "build.state == \"failed\""
        slack:
          message: "Build failure: Pipeline Generation"
          channels:
            - "#all-testing"