steps:
  # Simple trigger pipeline
  - label: ":rocket: Trigger Downstream Pipeline"
    trigger: "demokite"
    build:
      message: "Triggered from starter pipeline"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
    key: "trigger"