env:
  PIPELINE_VAR: "hello-from-pipeline"
  ANOTHER_VAR: "propagated-successfully"

steps:
  - label: ":kubernetes: Test mount-buildkite-agent equivalent"
    agents:
      queue: kubernetes
    command:
      - echo "--- Testing buildkite-agent binary availability"
      - which buildkite-agent
      - buildkite-agent --version
      - echo "--- Testing meta-data set/get"
      - buildkite-agent meta-data set "test-key" "test-value-123"
      - buildkite-agent meta-data get "test-key"
      - echo "--- Testing annotation"
      - buildkite-agent annotate "✅ Agent binary is mounted and working!" --style success --context mount-test
      - echo "--- Testing artifact upload"
      - echo "test artifact content" > /tmp/test-artifact.txt
      - buildkite-agent artifact upload /tmp/test-artifact.txt
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest

  - label: ":earth_americas: Test propagate-environment equivalent"
    agents:
      queue: kubernetes
    command:
      - echo "--- Testing pipeline env vars are propagated"
      - 'echo "PIPELINE_VAR=$$PIPELINE_VAR"'
      - 'echo "ANOTHER_VAR=$$ANOTHER_VAR"'
      - |
        if [ "$$PIPELINE_VAR" = "hello-from-pipeline" ]; then
          echo "✅ PIPELINE_VAR propagated correctly"
          buildkite-agent annotate "✅ Environment variables propagated!" --style success --context env-test --append
        else
          echo "❌ PIPELINE_VAR not propagated (got: $$PIPELINE_VAR)"
          exit 1
        fi
      - echo "--- Testing BUILDKITE_* vars are available"
      - 'echo "BUILDKITE_BUILD_ID=$$BUILDKITE_BUILD_ID"'
      - 'echo "BUILDKITE_PIPELINE_SLUG=$$BUILDKITE_PIPELINE_SLUG"'
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest

  - label: ":test_tube: Test step-level env override"
    agents:
      queue: kubernetes
    env:
      STEP_VAR: "step-level-value"
      PIPELINE_VAR: "overridden-at-step"
    command:
      - echo "--- Testing step-level env vars"
      - 'echo "STEP_VAR=$$STEP_VAR"'
      - 'echo "PIPELINE_VAR=$$PIPELINE_VAR (should be overridden)"'
      - |
        if [ "$$PIPELINE_VAR" = "overridden-at-step" ]; then
          echo "✅ Step-level override works"
        else
          echo "❌ Step-level override failed (got: $$PIPELINE_VAR)"
          exit 1
        fi
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
