steps:
  - label: "Test Build Creator vs Author"
    command: |
      echo "Build Creator: $BUILDKITE_BUILD_CREATOR"
      echo "Build Creator Email: $BUILDKITE_BUILD_CREATOR_EMAIL"
      echo "Build Author: $BUILDKITE_BUILD_AUTHOR" 
      echo "Build Author Email: $BUILDKITE_BUILD_AUTHOR_EMAIL"
      echo "Who should get error notifications: $BUILDKITE_BUILD_CREATOR"