steps:
  - label: "run tests"
    commands:
      - "mkdir -p artifacts"
      - "echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites><testsuite name=\"example\" tests=\"1\" failures=\"1\"><testcase name=\"test_example\" classname=\"ExampleTest\"><failure message=\"Test failed\">Expected true but got false</failure></testcase></testsuite></testsuites>' > artifacts/rspec-results.xml"
      - "ls -la artifacts/"
    artifact_paths: "artifacts/*"

  - wait: ~
    continue_on_failure: true

  - label: annotate
    plugins:
        - bugcrowd/test-summary#v1.8.0:
            inputs:
              - label: rspec
                artifact_path: artifacts/rspec*
                type: junit
            formatter:
              type: details
            context: test-summary