steps:
  - command: echo "Hello World"
    label: Generate pipeline
notify:
  - slack:
      channels:
        - '#all-testing'
      message: 'Build success: Pipeline Generation'
    if: build.state == "passed"