steps:
  - label: "Download all unknown artifacts"
    command: |
      ORG_SLUG="olabuildkite"
      GENERATOR_PIPELINE="plugin"
      
      # Get latest build
      LATEST_BUILD=$$(buildkite-agent api get "/v2/organizations/$$ORG_SLUG/pipelines/$$GENERATOR_PIPELINE/builds?state=passed&per_page=1" | jq -r '.[0].id')
      
      echo "Downloading ALL artifacts from build: $$LATEST_BUILD"
      
      # Download everything
      buildkite-agent artifact download "*" ./downloaded/ --build "$$LATEST_BUILD"
      
      echo "What did we get?"
      find ./downloaded/ -type f -exec echo "📁 {}" \; -exec head -3 {} \; -exec echo "---" \;