env:
  BUILDKITE_PLUGIN_S3_CACHE_BUCKET: "ola-buildkite-cache"

steps:
  # ===== ARTIFACTS APPROACH =====
  - label: ":package: Artifacts - Install"
    agents:
      queue: mac
    command: |
      uv venv .venv
      uv pip install -r requirements.txt
      tar -czf venv.tar.gz .venv
      buildkite-agent artifact upload venv.tar.gz

  - wait

  - label: ":white_check_mark: Artifacts - Use deps"
    agents:
      queue: mac
    command: |
      buildkite-agent artifact download venv.tar.gz .
      tar -xzf venv.tar.gz
      source .venv/bin/activate
      pip list

  - wait

  # ===== CACHE PLUGIN APPROACH =====
  - label: ":floppy_disk: Cache - Install"
    agents:
      queue: mac
    plugins:
      - cache#v1.8.1:
          backend: s3
          path: .venv-cached
          manifest: requirements.txt
          save: file
          compression: tgz
    command: |
      uv venv .venv-cached
      uv pip install -r requirements.txt --python .venv-cached/bin/python

  - wait

  - label: ":white_check_mark: Cache - Use deps"
    agents:
      queue: mac
    plugins:
      - cache#v1.8.1:
          backend: s3
          path: .venv-cached
          manifest: requirements.txt
          restore: file
          compression: tgz
    command: |
      source .venv-cached/bin/activate
      pip list
