agents:
  queue: "mac"
steps:
  - label: ":mag: Host Analysis"
    command: "env | grep BUILDKITE | wc -l && env | grep BUILDKITE | sort"

  - label: ":docker: Container Analysis"  
    command: "env | grep BUILDKITE | wc -l && env | grep BUILDKITE | sort"
    plugins:
      - https://github.com/Mykematt/docker-buildkite-plugin.git:
          image: "alpine:3.18"
          propagate-environment: true
          shell: ["/bin/sh", "-ec"]
