steps:
  - command: echo "Hello World"
    label: Generate pipeline
notify:
  - slack:
      channels:
        - '#all-testing'
      message: 'Build failure: Pipeline Generation'
      if: build.state == "failed"