notify:
  - github_commit_status:
      context: "buildkite/my-pipeline"
      if: build.branch == "main"

steps:
  - label: ":hammer: Build"
    command: |
      echo "Building on branch: \$BUILDKITE_BRANCH"
      echo "This step runs on all branches"
    
  - label: ":test_tube: Tests"
    command: |
      echo "Running tests..."
      sleep 5
      echo "Tests passed!"
    
  - label: ":rocket: Success"
    command: |
      echo "All steps completed!"
