env:
  BUILDKITE_PLUGIN_S3_CACHE_BUCKET: "buildkite-agent-cache-ola"

steps:
  - label: ":python: Install deps"
    agents:
      queue: mac
    plugins:
      - cache#v1.8.1:
          backend: s3
          path: .venv
          manifest: requirements.txt
          save: file
          compression: tgz
    command: |
      python3 -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt
      pip list

  - wait

  - label: ":test_tube: Step 2 - Use cached deps"
    agents:
      queue: mac
    plugins:
      - cache#v1.8.1:
          backend: s3
          path: .venv
          manifest: requirements.txt
          restore: file
          compression: tgz
    command: |
      if [ -d ".venv" ]; then
        echo "✅ .venv restored from cache!"
        source .venv/bin/activate
        pip list
      else
        echo "❌ .venv NOT found"
        exit 1
      fi

  - wait

  - label: ":test_tube: Step 3 - Also use cached deps"
    agents:
      queue: mac
    plugins:
      - cache#v1.8.1:
          backend: s3
          path: .venv
          manifest: requirements.txt
          restore: file
          compression: tgz
    command: |
      if [ -d ".venv" ]; then
        echo "✅ .venv restored from cache!"
        source .venv/bin/activate
        pip list
      else
        echo "❌ .venv NOT found"
        exit 1
      fi
