steps:
  - commands:
      - |
        if [ -n "$BUILDKITE_LABEL" ]; then
          buildkite-agent meta-data set "$BUILDKITE_LABEL" "true"
        fi
      - "export PS4='$'"
      - "echo 'steps:' > dynamic-pipeline.yml"
      - "echo '  - label: Dynamic Step' >> dynamic-pipeline.yml"
      - "echo '    command: echo Hello from generated pipeline' >> dynamic-pipeline.yml"
      - "buildkite-agent pipeline upload dynamic-pipeline.yml"
    label: "Generate pipeline"
    key: "execute_build_units_Generate-pipeline-e7e1"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 255
          limit: 2
        - exit_status: 128
          limit: 2
    agents:
      queue: "default"
    env:
      BUILD_JOB_PROJECT: "myproject"
notify:
  - slack:
      channels:
        - "#all-testing"
      message: "Build failure: Pipeline Generation"
    if: build.state == "failed"