steps:
  - label: "Test Success Job"
    command: |
      echo "This job will succeed"
      sleep 10
      echo "Success completed!"
    agents:
      queue: "mac"

  - label: "Test Failure Job"
    command: |
      echo "This job will fail"
      sleep 5
      echo "About to fail..."
      exit 1
    agents:
      queue: "mac"

notify:
  - email: "michael.omoge@buildkite.com"
    if: build.state == "passed"
  - email: "michael.omoge@buildkite.com"
    if: build.state == "failed"