agents:
  queue: "mac"
steps:
  - label: ":docker: Test Tracing Variables"
    command: |
      echo "--- Container Environment"
      env | grep -E 'BUILDKITE|OTEL' | sort
    plugins:
      - https://github.com/Mykematt/docker-buildkite-plugin-test.git#feature/propagate-tracing-vars:
          image: "alpine:3.18"
          propagate-environment: true
          shell: ["/bin/sh", "-ec"]
