env:
  PIPELINE_VAR: "hello-from-pipeline"

steps:
  - label: ":kubernetes: Test controller-level hooks"
    agents:
      queue: kubernetes
    command:
      - echo "--- Testing controller-level hook vars"
      - 'echo "CONTROLLER_HOOK_VAR=$$CONTROLLER_HOOK_VAR"'
      - 'echo "CONTROLLER_SECRET=$$CONTROLLER_SECRET"'
      - |
        if [ -n "$$CONTROLLER_HOOK_VAR" ]; then
          echo "✅ Controller-level hook vars ARE available"
        else
          echo "❌ Controller-level hook vars NOT available"
        fi
      - echo "--- Testing repo-level hook vars (should NOT be available)"
      - 'echo "HOOK_VAR=$$HOOK_VAR"'
      - |
        if [ -z "$$HOOK_VAR" ]; then
          echo "✅ Confirmed: repo-level hook vars are NOT propagated"
        else
          echo "Repo-level hook vars unexpectedly available"
        fi
      - echo "--- Testing pipeline env vars"
      - 'echo "PIPELINE_VAR=$$PIPELINE_VAR"'
    plugins:
      - kubernetes:
          podSpec:
            containers:
              - image: alpine:latest
