steps:
  - label: "Test redaction bug - interpolated"
    command: echo "This has interpolated secret: $TEST_SECRET"
    
  - label: "Test redaction fix - escaped"
    command: echo "This uses escaped variable: $$TEST_SECRET"
    env:
      TEST_SECRET: "hvs.CAESIXFXBZW"
