steps:
  # Test 1: Using $$ escaping
  - label: ":docker: configure image tag (test $$)"
    key: tag-create-double-dollar
    command: |
      TAG=$(echo "newtag-double-dollar")
      buildkite-agent meta-data set "TAG" "$$TAG"
      buildkite-agent step update "label" ":docker: TAG=$$TAG"
    agents:
      queue: ${BUILD_AGENT}

  # Test 2: Using \$ escaping  
  - label: ":docker: configure image tag (test \\$)"
    key: tag-create-backslash
    command: |
      TAG=$(echo "newtag-backslash")
      buildkite-agent meta-data set "TAG" "\$TAG"
      buildkite-agent step update "label" ":docker: TAG=\$TAG"
    agents:
      queue: ${BUILD_AGENT}

  # Test 3: Original single-line format with \$ (should fail)
  - label: ":docker: configure image tag (original format)"
    key: tag-create-original
    commands:
      - TAG=$(echo "newtag-original")
      - buildkite-agent meta-data set "TAG" "\${TAG}"
      - buildkite-agent step update "label" ":docker: TAG=\${TAG}"
    agents:
      queue: ${BUILD_AGENT}