agents:
  queue: "mac"
steps:
  - name: ":docker: Test with Explicit Vars"
    command: |
      echo "--- Container Environment"
      env | grep -E 'BUILDKITE|OTEL' | sort
    plugins:
      - docker#v5.12.0:
          image: "alpine:3.18"
          environment:
            - BUILDKITE_TRACING_BACKEND=opentelemetry
            - BUILDKITE_TRACING_SERVICE_NAME=buildkite
            - BUILDKITE_TRACING_PROPAGATE_TRACEPARENT=true
            - BUILDKITE_TRACING_TRACEPARENT=00-test-trace-id-01
          shell: ["/bin/sh", "-ec"]
          debug: true
