steps:
  - label: ":hammer: Verify BuildKit certificates"
    command: |
      set -euo pipefail
      
      # Verify certificates were installed by bootstrap hook
      if [ ! -f /etc/buildkit/ca.crt ] || [ ! -f /etc/buildkit/client.crt ] || [ ! -f /etc/buildkit/client.key ]; then
        echo "❌ BuildKit certificates not found. Bootstrap hook may have failed."
        exit 1
      fi
      
      echo "✅ BuildKit certificates installed successfully"
      ls -la /etc/buildkit/

  - label: ":docker: Test BuildKit connectivity"
    depends_on: "step-0"
    env:
      BUILDKIT_HOST: "tcp://10.0.2.181:1234"
      BUILDKIT_TLS_CERT: "/etc/buildkit/client.crt"
      BUILDKIT_TLS_KEY: "/etc/buildkit/client.key"
      BUILDKIT_TLS_CA_CERT: "/etc/buildkit/ca.crt"
    command: |
      set -euo pipefail
      
      echo "Testing connectivity to BuildKit daemon at $${BUILDKIT_HOST}..."
      
      # Test connection and list workers
      buildctl debug workers
      
      echo "✅ Successfully connected to remote BuildKit daemon"

  - wait

  - label: ":docker: Build test image"
    env:
      BUILDKIT_HOST: "tcp://10.0.2.181:1234"
      BUILDKIT_TLS_CERT: "/etc/buildkit/client.crt"
      BUILDKIT_TLS_KEY: "/etc/buildkit/client.key"
      BUILDKIT_TLS_CA_CERT: "/etc/buildkit/ca.crt"
    plugins:
      - ecr#v3.3.0:
          login: true
          account-ids:
            - "097340723131"
          region: us-east-1
    command: |
      set -euo pipefail
      
      # Create a simple test Dockerfile
      cat > Dockerfile.test <<'EOF'
      FROM alpine:latest
      RUN echo "Built with remote BuildKit" > /test.txt
      CMD ["cat", "/test.txt"]
      EOF
      
      echo "Building test image with remote BuildKit..."
      
      buildctl build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=Dockerfile.test \
        --output type=registry,name=097340723131.dkr.ecr.us-east-1.amazonaws.com/namespace-sample:buildkit-test,push=true
      
      echo "✅ Successfully built and pushed image using remote BuildKit"
