steps:
  - label: ":hammer: Verify BuildKit configuration"
    key: "step-0"
    command: |
      set -euo pipefail
      
      # Verify environment variable is set
      echo "BUILDKIT_HOST=${BUILDKIT_HOST}"
      echo "✅ BuildKit connection configured (TLS disabled for testing)"

  - label: ":docker: Test BuildKit connectivity"
    depends_on: "step-0"
    command: |
      set -euo pipefail
      
      echo "Testing connectivity to BuildKit daemon at $${BUILDKIT_HOST}..."
      
      # Test connection and list workers
      buildctl debug workers
      
      echo "✅ Successfully connected to remote BuildKit daemon"

  - wait

  - label: ":docker: Build test image"
    plugins:
      - ecr#v3.3.0:
          login: true
          account-ids:
            - "097340723131"
          region: us-east-1
    command: |
      set -euo pipefail
      
      # Create a simple test Dockerfile
      cat > Dockerfile.test <<'EOF'
      FROM alpine:latest
      RUN echo "Built with remote BuildKit" > /test.txt
      CMD ["cat", "/test.txt"]
      EOF
      
      echo "Building test image with remote BuildKit..."
      
      buildctl build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --opt filename=Dockerfile.test \
        --output type=registry,name=097340723131.dkr.ecr.us-east-1.amazonaws.com/namespace-sample:buildkit-test,push=true
      
      echo "✅ Successfully built and pushed image using remote BuildKit"
