steps:
  - label: "🧪 Test Environment Variable in Uploaded YAML"
    env:
      TEST_QUEUE_VALUE: "my-test-queue"
    command: |
      echo "=== Testing Environment Variable Approach ==="
      echo "runnin-queue: $BUILDKITE_AGENT_META_DATA_QUEUE"
      
      # Create YAML with bash variable substitution (not YAML interpolation)
      cat << EOF > test-step.yml
      steps:
        - label: "📋 Test Step with Queue"
          command: |
            echo "This step should run on my queue"
            echo "Original queue was: $running-queue"
          agents:
            queue: "$running-queue"
      EOF
      
      echo "=== Generated YAML ==="
      cat test-step.yml
      
      buildkite-agent pipeline upload test-step.yml
    agents:
      queue: "mac"
