steps:
  - label: "🧪 Test Pre-Checkout Hook on Kubernetes"
    command: |
      echo "===== Build Info ====="
      echo "Build Number: $BUILDKITE_BUILD_NUMBER"
      echo "Pipeline: $BUILDKITE_PIPELINE_SLUG"
      echo "Branch: $BUILDKITE_BRANCH"
      echo "Agent: $BUILDKITE_AGENT_NAME"
      echo ""
      echo "===== Files in workspace ====="
      ls -la
      echo ""
      echo "===== Git status ====="
      git status || echo "Not a git repo (or git not available)"
      echo ""
      echo "✅ If pre-checkout hook ran, you should see its output above!"
    agents:
      queue: kubernetes
