# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-webapp-service
  namespace: nginx-app
  labels:
    app: nginx-webapp
spec:
  selector:
    app: nginx-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer